version: "3.8"

services:
  nginx-service:
    build: ./docker/nginx
    container_name: nginx-container
    ports:
      - "5000:80"
    volumes:
      - .:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
      - postgres-service
    networks:
      - main

  php82-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/project
    networks:
      - main
    depends_on:
      - postgres-service
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: project_db
    networks:
      - main
volumes:
  postgres:
networks:
  main: